name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: 🔧 Install dependencies
      run: |
        pip3 install requests python-dotenv Flask flask-cors pylint
    - name: 🔬 Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
